---
title:Microsatellite summary analysis
output:pdf_document
---


### Main questions

This document contains all of the data required for analysing the AnswerALS data.


### 1.0 Package requirements

- change to current project root directory and include required packages 

```{r include = TRUE, message = FALSE, warning = FALSE}

library("here")
message("Project root:", here(), "\n")
require("HiCBricks")
require("GenomicRanges")
require("stringr")
require("ggplot2")
require("ggvenn")
require("DESeq2")

```

### 2.0 Include experiment matrix

- Let's first import the counts.

```{r include = FALSE, message = FALSE, warning = FALSE}

analysis_path <- here("final-figures", "figure-4")
save_dir <- file.path(analysis_path, "rdata_files")
plot_dir <- file.path(analysis_path, "plots")
input_dir <- file.path(analysis_path, "input_files")
output_dir <- file.path(analysis_path, "output_files")

dir.create(save_dir, recursive = T)
dir.create(plot_dir, recursive = T)
dir.create(input_dir, recursive = T)
dir.create(output_dir, recursive = T)

```

### 3.0 Imports

- Load data files 

```{r include = TRUE, message = FALSE, warning = FALSE}

repeat_ranges_list <- readRDS(here("final-figures","figure-1","rdata_files","00-repeat-ranges-introns-exons-with-mapping-to-exons-and-introns.rds"))
feature_ranges <- readRDS(here("05-simulated-reads-differential-profiling","rdata_files","01-all-merged-exonic-and-intronic-segments-in-genes.rds"))
sig_result_list <- readRDS(here("20-import-significant-events","rdata_files","02-significantly-differentially-expressed-events.rds"))
pan_als_diff_object <- readRDS(here("13-03-public-data","rdata_files","02-02-01-save-deseq2-all-samples-als-vs-control-differential-object.rds"))

```


- Setup 

```{r}

significant_de_event_df <- sig_result_list$significant_events
feature_ranges_with_repeats <- repeat_ranges_list$repeat_containing_ranges

significant_gene_df <- unique(significant_de_event_df[significant_de_event_df$pval < 0.05 & significant_de_event_df$region == "intron", c("gene_id", "status")])
status_split_by_genes <- split(significant_gene_df$status, significant_gene_df$gene_id)
genes_with_repeats <- names(status_split_by_genes[vapply(status_split_by_genes, function(x){
 "repeat_containing" %in% x
},T)])
unique_gene_ids <- unique(significant_gene_df$gene_id[significant_gene_df$gene_id %in% genes_with_repeats])
# gene_id_index <- round(seq_along(unique_gene_ids) / 1000)
# significant_gene_df$index <- gene_id_index[match(significant_gene_df$gene_id, unique_gene_ids)]
significant_gene_df <- significant_gene_df[significant_gene_df$gene_id %in% unique_gene_ids,]

feature_ranges$status <- "non_repeat_containing"
feature_ranges$status[feature_ranges$feature_id %in% feature_ranges_with_repeats$feature_id] <- "repeat_containing"
# feature_ranges_with_repeats[feature_ranges_with_repeats$gene_id %in% significant_intron_df$gene_id]

norm_matrix <- counts(pan_als_diff_object, normalized = TRUE)
experiment_matrix <- colData(pan_als_diff_object)

```

- Define function for getting model results

```{r}

return_model_output <- function(counts_matrix, gene_df, experiment_matrix, feature_ranges){
    # current_gene_df <- gene_df[gene_df$index == index,]
    # vst_matrix <- assay(counts_matrix)
    model_pval_df_list <- lapply(unique(gene_df$gene_id), function(x){
        message(x)
        current_exons <- feature_ranges[feature_ranges$gene_id == x & feature_ranges$type == "exon" & feature_ranges$hash_id %in% rownames(counts_matrix)]
        current_introns <- feature_ranges[feature_ranges$gene_id == x & feature_ranges$type == "intron" & feature_ranges$hash_id %in% rownames(counts_matrix)]
        if(length(current_exons) <= 1 | length(current_introns) <= 1 | length(unique(current_introns$status)) != 2){
            return(NULL)
        }
        control_exon_matrix <- counts_matrix[current_exons$hash_id, experiment_matrix$als_group == "ctrl"]
        control_intron_matrix <- counts_matrix[current_introns$hash_id, experiment_matrix$als_group == "ctrl"]
        als_exon_matrix <- counts_matrix[current_exons$hash_id, experiment_matrix$als_group == "als"]
        als_intron_matrix <- counts_matrix[current_introns$hash_id, experiment_matrix$als_group == "als"]

        if(any(min(c(nrow(control_exon_matrix), nrow(control_intron_matrix), nrow(als_exon_matrix), nrow(als_intron_matrix))) == 0)){
            return(NULL)
        }

        coords_matrix <- cbind(rep(seq_len(nrow(control_exon_matrix)), each = nrow(control_intron_matrix)),
            rep(seq_len(nrow(control_intron_matrix)), times = nrow(control_exon_matrix)))

        control_cor_val <- vapply(seq_len(nrow(coords_matrix)), function(y){
            # message(y)
            if(sd(control_exon_matrix[coords_matrix[y,1],]) == 0 | sd(control_intron_matrix[coords_matrix[y,2],]) == 0){
                return(NA)
            }
            cor_val <- cor(control_exon_matrix[coords_matrix[y,1],], control_intron_matrix[coords_matrix[y,2],])
            return(cor_val)
        },1)
        control_cor_matrix <- matrix(data = control_cor_val, nrow(control_exon_matrix), nrow(control_intron_matrix))
        rownames(control_cor_matrix) <- rownames(control_exon_matrix)
        colnames(control_cor_matrix) <- rownames(control_intron_matrix)
        als_cor_val <- vapply(seq_len(nrow(coords_matrix)), function(y){
            # message(y)
            if(sd(als_exon_matrix[coords_matrix[y,1],]) == 0 | sd(als_intron_matrix[coords_matrix[y,2],]) == 0){
                return(NA)
            }
            cor_val <- cor(als_exon_matrix[coords_matrix[y,1],], als_intron_matrix[coords_matrix[y,2],])
            return(cor_val)
        },1)
        als_cor_matrix <- matrix(data = als_cor_val, nrow(als_exon_matrix), nrow(als_intron_matrix))
        rownames(als_cor_matrix) <- rownames(als_exon_matrix)
        colnames(als_cor_matrix) <- rownames(als_intron_matrix)
        non_na_filter <- !is.na(als_cor_val) & !is.na(control_cor_val)

        dist_matrix <- (als_cor_matrix - control_cor_matrix)
        percent_contribution_matrix <- abs(dist_matrix) / rowSums(abs(dist_matrix))
        current_intron_status <- current_introns$status[match(colnames(percent_contribution_matrix), current_introns$hash_id)]
        repeat_containing_distances <- percent_contribution_matrix[,current_intron_status == "repeat_containing"]
        non_repeat_containing_distances <- percent_contribution_matrix[,current_intron_status != "repeat_containing"]
        if(all(is.na(repeat_containing_distances)) | all(is.na(repeat_containing_distances))){
            return(NULL)
        }
        test_results <- wilcox.test(repeat_containing_distances[!is.na(repeat_containing_distances)],non_repeat_containing_distances[!is.na(non_repeat_containing_distances)])
        return_df <- data.frame(gene_id = x,  
            n = length(als_cor_val[non_na_filter]),
            als_cor = mean(als_cor_matrix[,current_intron_status == "repeat_containing"],na.rm = T),
            ctrl_cor = mean(control_cor_matrix[,current_intron_status == "repeat_containing"],na.rm = T),
            mean_repeat_dist = mean(repeat_containing_distances,na.rm = T),
            mean_non_repeat_dist = mean(non_repeat_containing_distances,na.rm = T),
            pval = test_results$p.value)
        rownames(return_df) <- NULL
        return(list(return_df = return_df, als_cor_mat = als_cor_matrix,
            ctrl_cor_mat = control_cor_matrix,
            dist_matrix = dist_matrix,
            percent_contribution_matrix = percent_contribution_matrix))
    })
    return(model_pval_df_list)
}

```

- Get model output

```{r}

output_df_list <- return_model_output(counts_matrix = norm_matrix,
    gene_df = significant_gene_df,
    experiment_matrix = experiment_matrix,
    feature_ranges = feature_ranges)

```

- Aggregate all data

```{r}

output_df <- do.call(rbind, lapply(output_df_list, function(y){
    y$return_df
}))

percent_contribution_df <- do.call(rbind, lapply(output_df_list, function(y){
    if(is.null(y)){
        return(NULL)
    }
    return_df <- y$return_df
    current_matrix <- y$percent_contribution_matrix
    current_df <- reshape2::melt(current_matrix)
    current_df$group <- ifelse(current_df$Var2 %in% feature_ranges_with_repeats$hash_id, "repeat_containing", "non_repeat_containing")
    current_df$gene_id <- return_df$gene_id
    current_df <- current_df[,c("gene_id", "group", "Var1", "Var2", "value")]
    colnames(current_df) <- c("gene_id", "group", "exon", "intron", "value")
    current_df$exon <- as.character(current_df$exon)
    current_df$intron <- as.character(current_df$intron)
    return(current_df)
}))

correlation_df <- do.call(rbind, lapply(output_df_list, function(y){
    if(is.null(y)){
        return(NULL)
    }
    return_df <- y$return_df
    current_ctrl_matrix <- y$ctrl_cor_mat
    current_als_matrix <- y$als_cor_mat
    current_als_df <- reshape2::melt(current_als_matrix)
    current_ctrl_df <- reshape2::melt(current_ctrl_matrix)
    current_cor_df <- current_ctrl_df
    colnames(current_cor_df) <- c("exon", "intron", "ctrl_cor")
    current_cor_df$als_cor <- current_als_df$value
    current_cor_df$group <- ifelse(current_cor_df$intron %in% feature_ranges_with_repeats$hash_id, "repeat_containing", "non_repeat_containing")
    current_cor_df$gene_id <- return_df$gene_id
    current_cor_df <- current_cor_df[,c("gene_id", "group", "exon", "intron", "ctrl_cor", "als_cor")]
    colnames(current_cor_df) <- c("gene_id", "group", "exon", "intron", "ctrl_cor", "als_cor")
    current_cor_df$exon <- as.character(current_cor_df$exon)
    current_cor_df$intron <- as.character(current_cor_df$intron)
    return(current_cor_df)
}))

pval_df <- do.call(rbind, lapply(unique(percent_contribution_df$gene_id), function(x){
    current_contrib_df <- percent_contribution_df[percent_contribution_df$gene_id == x,]
    repeat_contrib <- current_contrib_df$value[current_contrib_df$group == "repeat_containing"]
    non_repeat_contrib <- current_contrib_df$value[current_contrib_df$group != "repeat_containing"]
    test_result <- wilcox.test(repeat_contrib, non_repeat_contrib)
    gt_test_result <- wilcox.test(repeat_contrib, non_repeat_contrib, alternative = "greater")
    data.frame(gene_id = x, two.sided = test_result$p.value, greater = gt_test_result$p.value)
}))


pval_df$padj <- p.adjust(pval_df$greater, method = "fdr")


split_by_gene <- split(percent_contribution_df, percent_contribution_df$gene_id)
median_contrib_df <- do.call(rbind, lapply(split_by_gene, function(temp_df){
    data.frame(gene_id = unique(temp_df$gene_id), 
        repeat_containing_contrib = median(temp_df$value[temp_df$group == "repeat_containing"], na.rm = T), 
        non_repeat_contrib = median(temp_df$value[temp_df$group != "repeat_containing"], na.rm = T))
}))

pval_df$repeat_contrib <- median_contrib_df[match(pval_df$gene_id, median_contrib_df$gene_id),"repeat_containing_contrib"]
pval_df$non_repeat_contrib <- median_contrib_df[match(pval_df$gene_id, median_contrib_df$gene_id),"non_repeat_contrib"]

candidate_genes <- pval_df[pval_df$padj < 0.05,]
saveRDS(object = candidate_genes, file = file.path(save_dir, "02-save-genes-where-the-variation-due-to-their-native-repeat-containing-intron-is-significant.rds"))
saveRDS(object = list(percent_contribution = percent_contribution_df, correlation_df = correlation_df, pval_df = pval_df), 
    file = file.path(save_dir, "01-save-model-output.rds"))


```
