---
title:Microsatellite summary analysis
output:pdf_document
---


### Main questions

This document contains all of the data required for analysing the AnswerALS data.


### 1.0 Package requirements

- change to current project root directory and include required packages 

```{r include = TRUE, message = FALSE, warning = FALSE}

library("here")
message("Project root:", here(), "\n")
require("HiCBricks")
require("GenomicRanges")
require("stringr")
require("ggplot2")
require("ggbeeswarm")

```

### 2.0 Include experiment matrix

- Let's first import the counts.

```{r include = FALSE, message = FALSE, warning = FALSE}

analysis_path <- here("final-figures","figure-2")
save_dir <- file.path(analysis_path, "rdata_files")
plot_dir <- file.path(analysis_path, "plots")
input_dir <- file.path(analysis_path, "input_files")
output_dir <- file.path(analysis_path, "output_files")

dir.create(save_dir, recursive = T)
dir.create(plot_dir, recursive = T)
dir.create(input_dir, recursive = T)
dir.create(output_dir, recursive = T)

```


### 3.0 Imports

- Load data files 

```{r include = TRUE, message = FALSE, warning = FALSE}

repeat_ranges_list <- readRDS(here("final-figures","figure-1","rdata_files","00-repeat-ranges-introns-exons-with-mapping-to-exons-and-introns.rds"))
feature_ranges <- readRDS(here("05-simulated-reads-differential-profiling","rdata_files","01-all-merged-exonic-and-intronic-segments-in-genes.rds"))
sig_result_list <- readRDS(here("20-import-significant-events","rdata_files","02-significantly-differentially-expressed-events.rds"))
nygc_object_list <- readRDS(here("13-nygc-consortium","rdata_files","03-02-list_of_counts_stat_samplesheet_from_nygc.rds"))
patient_df <- readRDS(here("13-nygc-consortium","rdata_files","03-05-nygc-patient-sampleinfo-datasheet.rds"))

```

### Analysis

- Generate TPM matrix

```{r}

feature_ranges_with_repeats <- repeat_ranges_list$repeat_containing_ranges
repeat_ranges <- repeat_ranges_list$repeat_ranges

sig_result_df <- sig_result_list$significant_events


repeat_containing_introns_df <- sig_result_df[sig_result_df$status == "repeat_containing" & 
    sig_result_df$region == "intron",]

non_repeat_containing_introns_df <- sig_result_df[sig_result_df$status != "repeat_containing" & 
    sig_result_df$region == "intron" & !(sig_result_df$gene_id %in% repeat_containing_introns_df$gene_id),]

non_repeat_containing_introns_df$cohort <- "public-data"
non_repeat_containing_introns_df$cohort[grepl(x = non_repeat_containing_introns_df$study, pattern = "nygc")] <- "nygc"
non_repeat_containing_introns_df$cohort[grepl(x = non_repeat_containing_introns_df$study, pattern = "answerals")] <- "answerals"

non_repeat_containing_introns_df$tissue_type <- "iPSCs"
non_repeat_containing_introns_df$tissue_type[grepl(x = non_repeat_containing_introns_df$study, pattern = "nygc")] <- "postmortem"


counts_matrix <- nygc_object_list$counts
temp_matrix <- counts_matrix / (width(feature_ranges)[match(rownames(counts_matrix), feature_ranges$hash_id)] / 1e3)
tpm_matrix <- t(t(temp_matrix) / (colSums(temp_matrix) / 1e6))


keep_hash_ids <- feature_ranges$hash_id[match(unique(non_repeat_containing_introns_df$feature_ids), feature_ranges$feature_id)]
keep_tpm_matrix <- tpm_matrix[keep_hash_ids,colnames(tpm_matrix) %in% patient_df$column_id]


```

- Generate liability data


```{r}

coldata_df_split <- split(patient_df, paste(patient_df$subject_id, patient_df$tissue))
patient_liability_df <- do.call(rbind, lapply(coldata_df_split, function(temp_df){
    return_df <- unique(temp_df[,-c(1,2,3,4,5,6,7,8,9,11,19,21)])
    current_columns <- temp_df$column_id
    if(nrow(return_df) > 1){
        if("N/A" %in% return_df$mnd_with_ftd & "Yes" %in% return_df$mnd_with_ftd){
            return_df <- return_df[return_df$mnd_with_ftd == "Yes",]
        }else if("N/A" %in% return_df$mnd_with_ftd & "No" %in% return_df$mnd_with_ftd){
            return_df <- return_df[return_df$mnd_with_ftd == "No",]
        }else if("tardbp" %in% return_df$type & "sporadic" %in% return_df$type){
            return_df <- return_df[return_df$type == "tardbp",]
        }else if("fus" %in% return_df$mutation & "none" %in% return_df$mutation){
            return_df <- return_df[return_df$mutation == "fus",]
        }else{
            stop(message(paste(return_df$subject_id, return_df$tissue)))
        }
    }
    
    current_tpm_vector <- Reduce("+", lapply(current_columns, function(x){
        keep_tpm_matrix[,x]  
    })) / length(current_columns)

    all_introns <- feature_ranges
    all_introns$signal <- current_tpm_vector[all_introns$hash_id]
    all_introns <- all_introns[!is.na(all_introns$signal)]

    current_threshold <- 1
    if(return_df$tissue %in% c("Cortex", "Cortex_Motor", "Cerebellum")){
        current_threshold <- 0.1
    }

    return_df$non_repeat_intron_expr_tpm <- sum(current_tpm_vector[current_tpm_vector > current_threshold])
    return_df$median_non_repeat_intron_expr_tpm <- median(current_tpm_vector[current_tpm_vector > current_threshold])
    return(return_df)
}))

```

- Attach metadata

```{r}

patient_liability_df$tissue <- droplevels(patient_liability_df$tissue)

patient_liability_df$tissue_group <- "spinal_cord"
patient_liability_df$tissue_group[patient_liability_df$tissue %in% c("Cortex", "Cortex_Motor", "Cerebellum")] <- "brain"
patient_liability_df$tissue <- factor(patient_liability_df$tissue, levels = c("Spinal_Cord_Cervical", "Spinal_Cord_Thoracic", "Spinal_Cord_Lumbar",
    "Cortex", "Cortex_Motor", "Cerebellum"))

rownames(patient_liability_df) <- NULL

saveRDS(object = patient_liability_df, file = file.path(save_dir, "01-save-nygc-non-rci-liabilities-in-patient-samples.rds"))

```
