---
title:Microsatellite summary analysis
output:pdf_document
---


### Main questions

This document contains all of the data required for analysing the AnswerALS data.


### 1.0 Package requirements

- change to current project root directory and include required packages 

```{r include = TRUE, message = FALSE, warning = FALSE}

library("here")
message("Project root:", here(), "\n")
require("HiCBricks")
require("GenomicRanges")
require("stringr")
require("rtracklayer")
require("ggplot2")

```

### 2.0 Include experiment matrix

- Let's first import the counts.

```{r include = FALSE, message = FALSE, warning = FALSE}

analysis_path <- here("41-magen-et-al-miRNA-seq")
save_dir <- file.path(analysis_path, "rdata_files")
plot_dir <- file.path(analysis_path, "plots")
input_dir <- file.path(analysis_path, "input_files")
output_dir <- file.path(analysis_path, "output_files")

dir.create(save_dir, recursive = T)
dir.create(plot_dir, recursive = T)
dir.create(input_dir, recursive = T)
dir.create(output_dir, recursive = T)

```

### 3.0 Imports

- Load data files 

```{r include = TRUE, message = FALSE, warning = FALSE}

repeat_ranges_list <- readRDS(here("final-figures/figure-1/rdata_files/00-repeat-ranges-introns-exons-with-mapping-to-exons-and-introns.rds"))
feature_ranges <- readRDS(here("05-simulated-reads-differential-profiling/rdata_files/01-all-merged-exonic-and-intronic-segments-in-genes.rds"))
sig_result_list <- readRDS(here("20-import-significant-events/rdata_files/02-significantly-differentially-expressed-events.rds"))

replication_data_list <- readRDS(here("41-magen-et-al-miRNA-seq/rdata_files/01-06-rci-counts-for-replication-set.rds"))
rci_stability_df <- readRDS(here("41-magen-et-al-miRNA-seq/rdata_files/01-05-rcis-with-stability-levels.rds"))

rci_counts_matrix <- replication_data_list$rci_counts
clinical_df <- replication_data_list$discovery_clinical_df
sampleinfo_df <- replication_data_list$sampleinfo_df

```

- Add these values back to the replication set

```{r}

stable_rcis <- rci_stability_df[rci_stability_df$std_err > -0.2, "rci"]

clinical_df <- clinical_df[,-seq(16, ncol(clinical_df)-3)]

replication_set_stable_rcis <- intersect(rownames(rci_counts_matrix), stable_rcis)

length(replication_set_stable_rcis) / length(union(rownames(rci_counts_matrix), stable_rcis))

rci_counts_matrix_transpose <- log2(t(rci_counts_matrix)[,replication_set_stable_rcis] + 1)

replication_clinical_with_counts_df <- cbind(clinical_df[match(sampleinfo_df$sample, clinical_df$index.case),], rci_counts_matrix_transpose[sampleinfo_df$sample,])

saveRDS(object = replication_clinical_with_counts_df, file = file.path(save_dir, "01-08-replication-clinical-with-mirna-counts-in-rcis.rds"))

```